### ISSUE TITLE
Would you please provide the pretrained model?

### ISSUE THREAD

**Issue by miaosiSari** [FrederikWarburg/Burst-Image-Deblurring#1]
I deeply appreciate your help!

**Comment by FrederikWarburg** [comment]
Hi @miaosiSari . 
Unfortunately, I don't have the pre-trained weights on my computer any more, so I'm afraid you will have to train the model. In my experience, the training doesn't take so long.
Let me know if you need help with anything else. 
Best
Frederik

**Comment by miaosiSari** [comment]
Thank you.
