### ISSUE TITLE
Could you provide the trained model weights?

### ISSUE THREAD

**Issue by Aupo293** [FrederikWarburg/Burst-Image-Deblurring#2]
Hi, I want to simply test the model. Could you provide the trained model weights? Thanks a lot.

**Comment by FrederikWarburg** [comment]
Hi, sorry I don't have the weight any longer. The training code is available, and it is quite fast to train. Let me know if you have problems. When I get more time, I'll upload a pre-trained model as I can see this repo is gaining attention :)
